### ISSUE TITLE
GodotString is in unicode, this means we could get a [char] for free, right?

### ISSUE THREAD

**Issue by lassade** [godot-rust/gdext#152]
Is there any way of getting the raw data of a GodotString as &'a [char] or &'a [u32]? Can you point a direction of how this could be done?

Rust uses utf8 by default but there is many crates that can handle unicode strings.

Edit: the String::to_utf32_buffer function is just copying data to a Vector so it must be UTF32

**Comment by Bromeon** [comment]
Godot stores characters [as `char32_t` in `String`](https://github.com/godotengine/godot/blob/master/core/string/ustring.h#L184) (behind a copy-on-write shared array).

To see whether we can expose a `&[char]` interface in Rust, we'd need clarification on:
1. Whether Rust `char` and C++ `char32_t` are layout-compatible on all platforms.
2. All characters representible can be mapped to `char`. To check whether Godot can e.g. store code points outside the _scalar-value_ ranges.
3. Whether it is possible to ever modify or deallocate a `String` while a `&[char]` reference is held to it (e.g. through GDScript, C++ or other Rust code). I guess not because CoW, but we would need a water-proof solution regarding edge cases.

Reference: https://doc.rust-lang.org/std/char

**Comment by Bromeon** [comment]
There is this FFI function which can be used to get a pointer to the start of the range, in `gdextension_interface.h`:
```rs
const char32_t *(*string_operator_index_const)(GDExtensionConstStringPtr p_self, GDExtensionInt p_index);
```

We do a similar thing for `PackedArray` already, so you could have a look there.

Such a solution would need to be heavily integration-tested, with various unicode strings entered from GDScript and Rust code.

**Comment by sayaks** [comment]
it would probably be very useful to set up proptest or even fuzzing if possible to help test this. as it can be kinda hard to manually cover enough edge cases.

**Comment by lassade** [comment]
Ok heres how I get a char slice

```
pub fn chars(&self) -> &[char] {
    unsafe {
        let s = self.string_sys();
        let len = interface_fn!(string_to_utf32_chars)(s, std::ptr::null_mut(), 0);
        let ptr = interface_fn!(string_operator_index_const)(s, to_i64(0)) as *const char;

        std::slice::from_raw_parts(ptr, len as usize)
    }
}
```

I tested by checking if every representable char in rust is equal as in the Godot char slice, and it is! 

Godot doesn't seem to like a few chars like the null terminator and the byte order mark, but it will be ok to get immutable char slice from a `GodotString`.

```
#[func]
fn test_chars(&self) {
    let mut bytes = [0u8; 16];
    for ch in 0..=char::MAX as u32 {
        if let Some(ch) = char::from_u32(ch) {
            let s = ch.encode_utf8(&mut bytes);
            let gs = GodotString::from_str(s).unwrap();
            let gs_chars = gs.chars();

            // not supported by godot, it just generates a empty string
            // \0 null terminator
            // \u{feff} endian ness
            if ch == '\0' || ch == '\u{feff}' {
                continue;
            }

            println!("{:?}", ch);
            assert_eq!(gs_chars.len(), 1);
            assert!(
                gs_chars[0] == ch,
                "char {:?} isn't equal on godot {}",
                ch,
                gs_chars[0] as u32,
            );
        }
    }
}
```

**Comment by lassade** [comment]
> it would probably be very useful to set up proptest or even fuzzing if possible to help test this. as it can be kinda hard to manually cover enough edge cases.

I don't think is needed, the `GodotString::to_utf32_buffer` just copies the data over to a buffer and return it, so it must be utf32 otherwise it should be an error

**Comment by Bromeon** [comment]
@lassade Thanks a lot for this! 👍 

Would you be interested in opening a pull request to add a `GodotString::chars()` method based on your proposal?

Regarding your test, I think we only need support actual "characters" (to be precise, [Unicode Scalar Values](https://www.unicode.org/glossary/#unicode_scalar_value)).

**Comment by sayaks** [comment]
the thing in conserned about here is that godot  might support all unicode code points and not just scalar values. in which case there would be godot chars that are not valid rust chars.

**Comment by Bromeon** [comment]
> the thing in concerned about here is that godot might support all unicode code points and not just scalar values. in which case there would be godot chars that are not valid rust chars.

Hm, very good point.

There is a FFI function to get write access to a `uint32_t*` pointer to the string, so at least _technically_, someone could write non-USV (unicode scalar values) into the string. So a GDExtension binding (not ours) could mess the string up, but may also cause problems in Godot itself.

More practical would be to find out if such strings can be constructed from GDScript. If yes, then a function
```rs 
fn chars(&self) -> &[char]; // panics, or:
fn chars(&self) -> Option<&[char]>;
```
would need to iterate the entire string to check validity first. 
O(n) is absolutely terrible for slice access -- then at best we could provide an iterator.

**Comment by sayaks** [comment]
> There is a FFI function to get write access to a `uint32_t*` pointer to the string, so at least _technically_, someone could write non-USV (unicode scalar values) into the string. So a GDExtension binding (not ours) could mess the string up, but may also cause problems in Godot itself.

If godot intends for chars to only be scalar values, then i would argue that a binding doing this is a bug in and of itself. Not saying we shouldn't think about it at all but at least then the bug wouldn't be on our end. Hopefully, if this is the case at least, there doesn't end up being a major library/plugin that does this.

**Comment by lassade** [comment]
Godot only allows for Scalar Values :)

```
extends Node2D

func _ready():
	var result_string = ""
	for i in range(0xD7FF + 1, 0xE000):
		result_string += char(i)
	pass
```

gives a bunch of `Unicode parsing error: Unpaired surrogate ...` errors

**Comment by Bromeon** [comment]
> Edit: Sadly the surrogate will still be appended to the string, but I think we can consider this one a error on the user end

I agree. Although we need to keep in mind that this will not just lead to logic errors, but possibly UB in Rust -- having a `char` pointing to a non-scalar-value is not allowed.

Maybe as a compromise, we can do a debug check (still O(n), but we can remove it if too slow):
```rs
fn chars() -> &[char] {
    let ptr: *const char = ...;
    debug_assert!(is_valid_unicode(ptr, len));
    unsafe { slice::from_raw_parts(ptr, len) }
}
```

Since you did already all the work, do you want to open a PR about this? 🙂 Let us know if you need any guidance!

**Comment by lassade** [comment]
@Bromeon sure thing

**Comment by lassade** [comment]
As far I can tell Godot [String::to_utf8_buffer](https://github.com/godotengine/godot/blob/9b9bb418cb1137e69b5131ec9fa7b41c0396db28/core/string/ustring.cpp#L1855) isn't handling invalid scalar values, maybe the cast of `char(surrogate)` should return a replacement char like �

**Comment by Bromeon** [comment]
We could just panic in those cases (in debug mode, due to the performance cost). I don't think we need to support non-Unicode strings.

**Comment by sayaks** [comment]
i feel like it'd be better to have a `chars` and `unsafe chars_unchecked` tbh.

**Comment by Bromeon** [comment]
> i feel like it'd be better to have a `chars` and `unsafe chars_unchecked` tbh.

But would you then add a O(n) check in `fn chars() -> &[char]`? That would be a _very_ surprising performance penalty for a function returning a slice, and in addition to that one that is barely ever needed (only if someone actively puts bad characters in a string).

Since Godot seems to recognize invalid chars upon insertion, I wonder if they could change their behavior to leave the string unchanged in such cases? Seems like a bug to print an error _yet still proceed_ with commiting said error.

**Comment by sayaks** [comment]
if there is a way to configure godot for that, it'd be great. but it's a subtle thing that's gonna be harder to guard against than most other cases of UB in this library. and it's not at all unreasonable to think that people would use the function on for instance entirely user-provided strings, which is never gonna be safe unless you add a check like this somewhere. that i think it might in this case be useful to maintain the unsafe/safe distinction. 

and besides, while it is an O(n) operation, it's likely gonna be more than fast enough in most cases, and we can document the distinction so that people may use the faster unsafe version when it matters. Like i think the vast majority of strings we'd use this on would be relatively small.

like we shouldn't create an over-proliferation of unsafe, that is one of the goals of these bindings. but forcing the user to always consider every single subtle unsafety issue seems like too big a move in the other direction, especially when the main reason here is just what's likely gonna be a minor performance optimization.

**Comment by sayaks** [comment]
I talked a bit with @Bromeon on discord in [this thread](https://discord.com/channels/723850269347283004/1083082176968527872). And we think it'd probably be best to have two versions of this function as i suggested, but name the safe checked version something that suggests it has the runtime cost. Similar to how `iter_shared` works for dictionary/array. Maybe `chars_checked` and `chars_unchecked`?

**Comment by Bromeon** [comment]
> But this should be fixed on Godot end, but that should take a bit longer to get merged. I think Godot defaults to UB instead of panic like rust usually handle thinks, because a panic will close the editor and make you lose your work, maybe, I don't know.

Yes, we should at least start a discussion in a Godot issue or so; chances are that we will end up needing only 1 method later. But as you say, this will take a while. Do you have time to file an issue with Godot or should I do it later this week?

For now I agree with @sayaks: `chars_checked` + unsafe `chars_unchecked` 🙂

**Comment by lassade** [comment]
The PR is done, now is just have to open a Godot issue
