### ISSUE TITLE
Possible implementations of rust convenience traits

### ISSUE THREAD

**Issue by lilizoey** [godot-rust/gdext#297]
Many standard rust types use various convenience traits to extend their functionality, we should consider which of these convenience traits we can and should implement.

An attempt at an exhaustive list of such traits:

- [`Borrow`](https://doc.rust-lang.org/std/borrow/trait.Borrow.html)/[`BorrowMut`](https://doc.rust-lang.org/std/borrow/trait.BorrowMut.html)/[`ToOwned`](https://doc.rust-lang.org/std/borrow/trait.ToOwned.html)
- [`Clone`](https://doc.rust-lang.org/std/clone/trait.Clone.html)
- [`Eq`](https://doc.rust-lang.org/std/cmp/trait.Eq.html)/[`PartialEq`](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html)
- [`Ord`](https://doc.rust-lang.org/std/cmp/trait.Ord.html)/[`PartialOrd`](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html)
- [`From`](https://doc.rust-lang.org/std/convert/trait.From.html)/[`TryFrom`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) (`Into` shouldn't be directly implemented)
- [`AsRef`](https://doc.rust-lang.org/std/convert/trait.AsRef.html)/[`AsMut`](https://doc.rust-lang.org/std/convert/trait.AsMut.html)
- [`Default`](https://doc.rust-lang.org/std/default/trait.Default.html)
- [`Error`](https://doc.rust-lang.org/std/error/trait.Error.html)
- [Various fmt traits](https://doc.rust-lang.org/std/fmt/index.html#traits). `Debug`, `Display`, and `Write` being most important.
- [`Future`](https://doc.rust-lang.org/std/future/trait.Future.html)
- [`IntoFuture`](https://doc.rust-lang.org/std/future/trait.IntoFuture.html)
- [`Hash`](https://doc.rust-lang.org/std/hash/trait.Hash.html)
- [The iterator traits](https://doc.rust-lang.org/std/iter/index.html#traits)
- [`ToSocketAddrs`](https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html)
- [Operator overloading](https://doc.rust-lang.org/std/ops/index.html#traits)
- [`SliceIndex`](https://doc.rust-lang.org/std/slice/trait.SliceIndex.html)
- [`FromStr`](https://doc.rust-lang.org/std/str/trait.FromStr.html)
- [`Wake`](https://doc.rust-lang.org/std/task/trait.Wake.html)

**Comment by lilizoey** [comment]
As a general thought, i think we should try to implement most of these where it makes sense. As that helps rhe bindings be used throughout the rust ecosystem.

For some specific thoughts:

We could implement `Borrow`/`BorrowMut`/`ToOwned` for converting between `T` and `Gd<T>`.

Do we need our own `Share` trait? it basically functions like `Clone` but is not as flexible as `Clone` because other crates dont know about it. Could we just replace it with `Clone`? There are already types in the rust std whose `Clone` impl functions like share does, like `Rc`/`Arc`.

We could implement `From`/`TryFrom` more eagerly than we currently do. which could help with cross compatability of crates.

**Comment by Ogeon** [comment]
The lack of `Clone` for `Gd` is a bit inconvenient since it prevents deriving `Clone` for types that directly contain a `Gd`. Not to mention generic code that doesn't know about `Share`.

**Comment by Ogeon** [comment]
I can definitely see how it's tricky to decide on the right API and semantics and thanks for linking the previous discussion. My spontaneous expectation, from my own use and understanding so far, would be that `Clone` would be as close as possible to what gdscript does when assigning a value to a variable. 🤔 I mean such that

```gdscript
var a := MyType.new()
var b := a
```

basically corresponds to

```rust
let a: Gd<_> = MyType::new(); // made up example fn
let b = a.clone();
```

But I'm not here to revive the discussion and I'm sure I'm missing a ton of weird cases with my anecdotes, anyway. 😬

**Comment by Bromeon** [comment]
That's an interesting perspective. It would mean that copy-on-write types like `GodotString` or `PackedArray` would be deep-copied (upon first write), whereas reference-counted ones like `Array`, `Dictionary` or `Gd<T: RefCounted>` would be shared.

It means the trait (`Clone` or `Share`) no longer expresses what types of copy semantics are used; however a Godot user would likely need to know this anyway when working with the types.

**Comment by Ogeon** [comment]
This is specifically for `Clone`, which I'm thinking is the "default" way of copying. I'm hoping it would be easier to memorize things and prevent mistakes if the rules are the same in both rust and gdscript. But I don't know if it's too messy or hard to implement.

I think there's still room for more explicit methods or traits where it makes sense, so `Gd` could in theory also have a `bikeshed_clone_inner` function that clones the data. And `Share` can maybe stay for things that explicitly can be shared, if that's useful. Hopefully not in a way that results in multipe similar options again...

Would `Clone` even work normally on a `GodotClass`, considering it has the `base` reference that I'm assuming would need to be replaced? 👀 I suppose `Base` can have a special clone implementation?

**Comment by Bromeon** [comment]
> Would `Clone` even work normally on a `GodotClass`, considering it has the `base` reference that I'm assuming would need to be replaced? 👀 I suppose `Base` can have a special clone implementation?

Not in the general case -- it works well for types that are "data bundles", i.e. classes that:
* inherit `RefCounted`
* don't have a `#[base]` attribute
* can thus live outside a `Gd<T>`, and be constructed using `Gd::new(obj)`

They typically have quite different usage than regular classes. One thing that can be useful for them is value semantics. But maybe there should be a dedicated `DeepClone` trait in such cases.

**Comment by Ogeon** [comment]
Oh, I didn't realize it was possible to omit the `#[base]` attribute, but I guess I didn't try either. 🤔 But it makes sense to want to treat those types like more regular Rust types, at least outside the `Gd`.

**Comment by bluenote10** [comment]
> We could maybe implement Borrow/BorrowMut/ToOwned for converting between T and Gd<T>.

Due to https://github.com/rust-lang/rust/issues/41906 I'm always a bit scared of using a `use std::borrow::Borrow;` at module level (because it will break typical usage `Rc<RefCell<T>>`). So we should be a bit careful that this doesn't lead to similar ambiguity issues.

**Comment by Bromeon** [comment]
I'm also a proponent of "just because we can, doesn't mean we should" 🙂 

Before implementing traits like `Borrow`, I'd like to see _practical_ use cases in the context of gamedev, not theoretical generic scenarios. In case of doubt, we should wait and see if people truly run into scenarios, where these would solve something that's not already possible with the existing API.

**Comment by Bromeon** [comment]
As it is, this issue is too open-ended and has no clear actionable or condition after which it can be closed. It thus becomes a candidate for "perpetually open", which I'd like to avoid.

Plus, I'm not a big fan of the approach, as stated before. These traits should be justified by use cases, like every other feature. Doing use-case-driven development ensures that all code in existence is actually useful (by definition) and has gone through consideration by maintainers. The alternative is that we end up adding a lot of code that might not benefit anyone at all, yet we keep paying the maintenance cost until eternity.

Of course, simple things like `Debug` don't need a huge justification every time. But for many of the above traits, the added value is not immediately obvious.

There have already been several issues and PRs toward specific traits:
- #553
- #201 
- #528 
- #505 
- #536

And some should likely be tracked around the time when a specific feature is going to be implemented (e.g. `Future`/`IntoFuture`/`Wake` if we are starting an async implementation, far in the future -- no pun intended).

If you see traits in the above list that are missing and would add a lot of value _right now_, please speak up. We can then discuss and track those separately. I will close this issue by end of next week, so we keep the tracker focused on more concrete and higher-priority issues -- of which there are a lot 😀
