### ISSUE TITLE
Rust -> GDScript -> Rust calls limitation

### ISSUE THREAD

**Issue by Soremwar** [godot-rust/gdext#383]
A lot of traditional GDScript approachs applied to GDext will likely end up in the `This often occurs when calling a GDScript function/signal from Rust, which then calls again Rust code.` message right now. Ex: Trying to call a function from a parent node

Is this a limitation that is expected to be solved? Or is this something that must be work around. If that is so, what would be the recommended way to do this?

**Comment by Bromeon** [comment]
This is the same problem as #338.

TLDR: as soon as a method call leaves Rust (goes to the Godot engine or GDScript code), the Rust borrow checker no longer keeps track of reborrows. The borrow on the Rust-side object persists across the call. So if the engine calls back to the same object on the Rust side, a _new_ borrow is created -- which can fail if there's a live `&mut T`.

I'm not sure if it's possible to solve, but it's certainly hard; see the other issue.

**Comment by Bromeon** [comment]
Btw, regarding workarounds: you could use `&T` instead of `&mut T` as receivers, so that double-borrows are allowed.
This of course comes with its own limitations, such as using the `std::cell` types for interior mutability.

Another approach is to design your data flow in a way such that recurring Rust -> GDScript -> Rust calls are not necessary. For example, Rust can query information from GDScript and act upon that -- GDScript would return instead of call another Rust function.
