### ISSUE TITLE
[meta feature request] Squash-merge on pull requests

### ISSUE THREAD

**Issue by patataofcourse** [godot-rust/gdext#385]
From [Contributing.md](https://github.com/godot-rust/gdext/blob/b4e6fd6c9c23e0fd3a124c2893a9592c861ab780/Contributing.md?plain=1#L26):
> Since we use the bors bot to merge PRs, we can unfortunately not squash commits upon merge.

However, since #337 was merged, this isn't true anymore, and PRs can be squashed on merge automatically.

I'm not sure if this is the way the project wants to go, since it involves putting *every* commit in a PR into the same squashed commit, even if they're two logically different features, but it would be nice to know what the stance of the repo mantainer(s) is (and for the Contributing.md to be updated to reflect that as well)

**Comment by Bromeon** [comment]
> I'm not sure if this is the way the project wants to go, since it involves putting _every_ commit in a PR into the same squashed commit, even if they're two logically different features

The problem is the same as before: it's all-or-nothing. [bors also supports `use_squash_merge`](https://bors.tech/documentation/) in `bors.toml`, but we cannot decide it per pull request.

If you look at [recently merged pull requests authored by me](https://github.com/godot-rust/gdext/pulls?q=is%3Apr+is%3Aclosed+is%3Amerged+author%3Abromeon), many of them contain multiple commits. Squashing them would mean we lose the granularity of semantically unrelated changes and have a harder time reverting or bisecting. Creating a separate PR for each tiny change adds a lot of useless administrative overhead.

Also, I don't think it's too much to ask for people to clean up PRs before getting them in a mergeable state -- I'm usually happy to assist when it comes to the "how to" part in git 🙂


---

> but it would be nice to know what the stance of the repo mantainer(s) is (and for the Contributing.md to be updated to reflect that as well)

[The current version of `Contributing.md`](https://github.com/godot-rust/gdext/blob/b4e6fd6c9c23e0fd3a124c2893a9592c861ab780/Contributing.md) already expresses that, no? Only the bors part is outdated as far as I can see.

> ### One commit per logical change
> 
> This makes it easier to review changes, later reconstruct what happened when and -- in case of regressions -- revert individual commits. The exception are tiny changes of a few lines that don't bear semantic significance (typos, style, etc.). Larger code style changes should be split though.
>
> If your pull request changes a single thing, please squash the commits into one. Avoid commits like "integrate review feedback" or "fix rustfmt". Instead, use git commit --amend or git rebase -i and force-push follow-up commits to your branch (git push --force-with-lease). Since we use the bors bot to merge PRs, we can unfortunately not squash commits upon merge.

**Comment by patataofcourse** [comment]
yeah it would specifically be the bors part cause it was a bit confusing, is all

**Comment by patataofcourse** [comment]
Done as of 43f5d2f
