### ISSUE TITLE
Crash when using can_drop_data

### ISSUE THREAD

**Issue by DSOverlord** [godot-rust/gdext#394]
I have the game crashing in almost any scenario using drop_data. Even with something as simple as this:
```rust
    fn get_drag_data(&mut self, _at_position: Vector2) -> Variant {
        let drag_data = "test".to_variant();
        return drag_data;
    }
```
```rust
    fn can_drop_data(&self, _at_position: Vector2, data: Variant) -> bool {
        godot_print!("{:?}", data);
        return false;
    }
```

Am I doing something wrong, or is this a bug?

**Comment by lilizoey** [comment]
Do you get any error messages? Either in godot or if you could try running godot from the terminal/command line and see if you get any error messages there?

**Comment by DSOverlord** [comment]
Here are all the messages I'm getting:
```
Variant(ty=String, val=test)
Variant(ty=String, val=)
Variant(ty=String, val=)
Variant(ty=String, val=)
Variant(ty=String, val=)
Variant(ty=String, val=)
Variant(ty=String, val=)
Variant(ty=String, val=)
malloc(): smallbin double linked list corrupted
```

**Comment by lilizoey** [comment]
i can reproduce this at least, so it does seem like a bug, not entirely sure why it's happening though

**Comment by AckslD** [comment]
@lilizoey @DSOverlord I think I had the same issue, see:

https://discord.com/channels/723850269347283004/1190796227235823647

I wonder if the issue is that nothing owns the variant so its memory gets freed in the meantime somehow? I tried in my example to store the object (in my case an array and in yours a string) in the `Control` node which seems to avoid the crash but it still doesn't pass the correct array to `drop_data`. See more details in the above discord thread.

**Comment by Bromeon** [comment]
@DSOverlord @AckslD there have been some FFI improvements/fixes in the meantime, can you still reproduce this issue?

(Well possible that yes, just want to make sure we're not tracking outdated tasks :wink: )

**Comment by AckslD** [comment]
@Bromeon the crashes I was reproducing in [this small example repo](https://gitlab.com/AckslD/tmp-godot) now indeed seem fixed and it does not crash anymore :rocket: So from my part this can be closed.

**Comment by DSOverlord** [comment]
I also tested on my example and the glitches are fixed. So I think this issue can be closed.
