### ISSUE TITLE
Github actions Windows build fails with "LLVM ERROR: out of memory"

### ISSUE THREAD

**Issue by pka** [godot-rust/gdext#450]
When building a basic extension with a GH action [workflow](https://github.com/pka/godot-geo-tile-loader/blob/622ca8b/.github/workflows/build.yml), the Windows build fails with

```
LLVM ERROR: out of memory
Allocation failed
error: could not compile `godot-ffi` (lib)

Caused by:
  process didn't exit successfully: `rustc --crate-name godot_ffi --edition=2021 C:\Users\runneradmin\.cargo\git\checkouts\gdext-76630c89719e160c\7594e9c\godot-ffi\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=46ec6a1d31a818b0 -C extra-filename=-46ec6a1d31a818b0 --out-dir D:\a\godot-geo-tile-loader\godot-geo-tile-loader\rust\target\x86_64-pc-windows-msvc\release\deps --target x86_64-pc-windows-msvc -L dependency=D:\a\godot-geo-tile-loader\godot-geo-tile-loader\rust\target\x86_64-pc-windows-msvc\release\deps -L dependency=D:\a\godot-geo-tile-loader\godot-geo-tile-loader\rust\target\release\deps --extern paste=D:\a\godot-geo-tile-loader\godot-geo-tile-loader\rust\target\release\deps\paste-5f7b09c9d188a8c9.dll --cap-lints allow -D warnings --cfg "since_api=\"4.1\"" --cfg "before_api=\"4.2\"" --cfg "gdextension_minor_api=\"4.1\"" --cfg "gdextension_exact_api=\"4.1.1\""` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
```

This is probably a low memory limit of the GH VM, but since this is a common use case, we should have a workaround for that?

**Comment by Bromeon** [comment]
I don't know, have you looked at our Windows builds in GitHub Actions? They don't have this problem.

Do you need LLVM at all? bindgen isn't required unless you specify the `custom-godot` feature.

**Comment by Bromeon** [comment]
Independently of the failure here, I plan to slightly change the way how function pointers are stored, as this has caused problems in WASM as well.

**Comment by pka** [comment]
The current workaround is to do a debug build.

I couldn't find a release build in the gdext workflows. How could I disable LLVM in the Windows CI?

**Comment by Bromeon** [comment]
You didn't mention it was a release build, that's an important detail 😉 

Eventually, I think we have to get release builds into our own pipeline. However, I won't work on CI for the next few days unless there are emergencies, since I just wasted 2 evenings on minor issues like #449 and I'd like to do more productive stuff for a change.

So I'm not sure if there's a workaround right now. You could try to limit the amount of classes in [the `SELECTED_CLASSES` constant](https://github.com/godot-rust/gdext/blob/master/godot-codegen/src/codegen_special_cases.rs#L114-L114) and build with `default-features = false`. Other than that, one option might be to replace [the arrays in the function pointer tables](https://github.com/godot-rust/gdext/blob/master/godot-codegen/src/central_generator.rs#L304-L304) with `Vec`s. It's all a bit involved, that's really in case you can't wait and need something right now.

**Comment by Bromeon** [comment]
@pka Can you try if this also happens with the new `lazy-function-tables` Cargo feature?

**Comment by pka** [comment]
@Bromeon Tested with latest `master` and it did compile successfully with `--release` and `--features godot/lazy-function-tables --release`. Thanks!
