### ISSUE TITLE
Jetbrains IDEs don't support static analysis of generated code in `OUT_DIR`

### ISSUE THREAD

**Issue by Bromeon** [godot-rust/gdext#506]
We can currently not generate sources inside `target` (via `OUT_DIR`), because CLion/RustRover do not recognize symbols in that directory, completely breaking user experience. This is however likely a blocker for #2 (unless we consider `#[cfg]` shenanigans).

Upstream: [RUST-12312](https://youtrack.jetbrains.com/issue/RUST-12312/Unsupported-cases-with-include-macros) on YouTrack. 
Please upvote if you can. It looks like a solution is already being worked on.

**Comment by Bromeon** [comment]
Looks like the above issue was closed 3 days ago, but there was no comment.
Will need to test on latest RustRover...

**Comment by bluenote10** [comment]
>  Will need to test on latest RustRover...

Did you already give it a try? From that (upstream) issue it is still a bit unclear if something has changed, but at least [yesterday 3 related meta issues got closed](https://youtrack.jetbrains.com/issues?q=links:RUST-12312).

If I remember correctly this is basically the only thing preventing publishing on crates.io (#2), right?

I'm wondering how exactly it affects the publishing (I'm not a CLion user): Wouldn't it be possible for CLion users to _still_ consume gdext just via git if consuming it via crates.io is what doesn't work? Or would the mere existence of the crate on the index cause issues? Or is it more a problem of communicating/documenting that CLion users must not use the published crate yet? Perhaps this could be mitigated by only using [pre-releases / beta versions](https://stackoverflow.com/questions/46373028/how-to-release-a-beta-version-of-a-crate-for-limited-public-testing) for the time being.

---------------

It would really be great to have a first release on crates.io. I have quite a few experimental projects, and working just with git hashes makes it a bit hard to keep an overview of what I'm using where (apparently I'm using 19 different versions in total :see_no_evil:). I'm also copy/pasting various convenience/utils functions from project to project, which is pretty messy. Today I wanted to consolidate that a little bit and start publishing my own utils crate on crates.io, but it turns out that publishing a crate is not allowed if it depends on another unpublished crate (understandably of course). And tracking yet another dependency only via git isn't ideal either. Looks like [this crate](https://crates.io/crates/gdext-egui) is in a similar situation.

**Comment by Bromeon** [comment]
Crates release is on my list for 2024, but there are a few more important issues, e.g. currently I'm looking into the hot reloading fix + a way to avoid future regressions (as it's already the third). 

The release is not just blocked by the Jetbrains issue, but needs quite a bit of infra work to automate. There are some open questions regarding how different Godot versions are provided, which one is chosen by default, and how users can select their own.
