### ISSUE TITLE
`ConvertError` is neither `Send` nor `Sync`

### ISSUE THREAD

**Issue by Dheatly23** [godot-rust/gdext#523]
I used `anyhow` as my error handling, and `ConvertError` is not `Send` nor `Sync` breaks my code when updating (commit ID 77e3b958e53e59f19b4d6ef23a83f01eb6304123). There should be no reason `ConvertError` can't be both.

**Comment by Dheatly23** [comment]
To convert it to `anyhow::Error`. Without it, i can't `?` operator it.

**Comment by Bromeon** [comment]
> . There should be no reason `ConvertError` can't be both.

That's not true by the way, some errors store a `Variant` in the context. `Variants` cannot be generally thread-safe, because they can contain arbitrary objects (`Gd<T>`).

When we make `ConvertError: Send + Sync`, we cannot provide [`ConvertError::value()`](https://godot-rust.github.io/docs/gdext/master/godot/prelude/meta/struct.ConvertError.html#method.value) any longer, because values cannot be stored thread-safely in general. We could maybe store the `Debug` representation of the value as a string, but that would lose some information about the original value...

**Comment by Dheatly23** [comment]
Well that sucks. But looking at source code, the type is erased through `Box` and can't be recovered (no `Any`).

**Comment by Bromeon** [comment]
This API is relatively new, so I'm not sure if there's a concrete use case for `value()` anyway. I would assume most people are interested in good error messages more than anything else, and we should ensure that that contains the value.

I'll have a look at this.

**Comment by lilizoey** [comment]
> This API is relatively new, so I'm not sure if there's a concrete use case for `value()` anyway. I would assume most people are interested in good error messages more than anything else, and we should ensure that that contains the value.
> 
> I'll have a look at this.

We can probably just completely erase value and turn it into a string representation tbh since that's the most important part.

**Comment by Dheatly23** [comment]
Just tested it, so far it works flawlessly.
