### ISSUE TITLE
 Understanding callable closure for connect function

### ISSUE THREAD

**Issue by gmae199boy** [godot-rust/gdext#533]
hello. First of all, I am a beginner in godot and rust.

I implemented the `mouse_enter()` function using IArea2D, but this did not work.

So I implemented `self.area.connect("mouse_entered".into(), callable);` inside the ready() function. This perfectly calls closure when the mouse is hovered over.

However, I don't know how to write this.

``` 
let a = Callable::from_fn("mouse_entered_a", |args| {
            self.is_mouse_over = true;
            Ok(true.to_variant())
});
```

self is `borrowed data escapes outside of method 'self' escapes the method body here` This error occurs and cannot be used. Therefore, I'm focusing on the `Ok("".to_cariant())` that returns inside the closure, but I don't know where to get this.

How can I get the value when the closure or `mouse_entered` signal is called?

**Comment by Bromeon** [comment]
The Rust error is on point, you cannot keep a reference to `self` due to the borrow-checker. The callable exists independently of `self` and might even outlive it.

You have two options:
1. Declare a `#[func]` and connect the signal to that one, using `Gd::callable` (see docs).
   This is likely the easiest.
2. If you want to keep on using `from_fn` (not recommended), you need to pass in a `Gd<Self>` rather than `&self`. Declare a local variable initialized to `self.to_gd()` and pass it into the `move` closure.

Btw, this issue tracker is mostly intended for confirmed problems. For help about usage, consider joining [our Discord channel](https://discord.gg/aKUCJ8rJsc) 🙂

**Comment by gmae199boy** [comment]
Thank you for quick response. I'll just ask this question and move it to the discord channel.

```
#[godot_api]
impl IArea2D for CardArea {
    // constructor
    fn init(area: Base<Area2D>) -> Self {
        Self {
            area,
            is_mouse_over: false,
            is_mouse_up: false,
        }
    }

    fn ready(&mut self) {
        // let a = Callable::from_fn("mouse_entered_a", |args| {
        //     self.is_mouse_over = true;
        //     Ok(true.to_variant())
        // });

        let a = Callable::from_object_method(&self.area, "is_mouse_over");

        self.area.connect("mouse_entered".into(), a);
    }
}

#[godot_api]
impl CardArea {
    #[func]
    pub fn is_mouse_over(&self) -> bool {
        godot_error!("is_mouse_over: {:?}", self.is_mouse_over);
        self.is_mouse_over
    }
}
```


I changed the code according to the answer. This is my code.

If you do this, in godot client
```
E 0:00:03:0789 <function unset>: is_mouse_over: false
  <C++ source> src\card.rs:82 @ <function unset>
``` 
This error appears. Isn’t this how you use it?
