### ISSUE TITLE
Extension class instances constructed in rust cannot be reloaded

### ISSUE THREAD

**Issue by TitanNano** [godot-rust/gdext#543]
Since Godot 4.2 the engine has extension (hot) reloading. During reloading, the engine [creates a backup of the class properties that have been exposed to godot](https://github.com/godotengine/godot/blob/9d1cbab1c432b6f1d66ec939445bec68b6af519e/core/extension/gdextension.cpp#L1015-L1056) and once the extension has been reloaded [it recreates the extension parts of all the classes](https://github.com/godotengine/godot/blob/9d1cbab1c432b6f1d66ec939445bec68b6af519e/core/extension/gdextension.cpp#L1138-L1150) that have been defined by the extension. 

Important here is that the engine tries to track all the instances which have been created for an extension class so that they can be reloaded later on. This happens in [`ClassDB::instantiate`](https://github.com/godotengine/godot/blob/9d1cbab1c432b6f1d66ec939445bec68b6af519e/core/object/class_db.cpp#L370-L374). 

Unfortunately when gdext is creating classes from inside rust, it never goes through `ClassDB::instantiate`. It rather creates a new instance of the base class via `ClassDB::instantiate` and then assigns the rust instance to that base object via [`object_set_instance`](https://github.com/godot-rust/gdext/blob/92dce9c4787670b7b209d402d4b1feea430eb9cc/godot-core/src/registry.rs#L574). The engine does not track these assignments as new instances of an extension class.

When the extension is then reloaded, none of the class instances are reloaded as the `instance` list of the `extension_class` is empty.

-----

Trying to follow the code paths of Godot and gdext it appears that `Gd::default_instance()` should not directly call [`crate::callbacks::create`](https://github.com/godot-rust/gdext/blob/92dce9c4787670b7b209d402d4b1feea430eb9cc/godot-core/src/obj/gd.rs#L356C1-L356C82) but rather call `ClassDB::instantiate`. 

Direct access to `crate::callbacks::create_custom` via `Gd::from_init_fn` also seems currently problematic, as it bypasses the instance tracking as well. 

On the other hand, the engine could also move the instance tracking to `ClassDB::set_object_extension_instance`.

**Comment by Bromeon** [comment]
`ClassDB::instantiate()` cannot be generally used, as it takes no arguments. It thus can't create Rust classes that don't have an `init` function, and requiring the latter is too limiting. For example, `Gd::from_init_fn()` allows the user to pass in arbitrary context.

Otherwise, we'd need to have an intermediate zombie state (something like `Option<UserInstance>`) which is then properly initialized _after_ `ClassDB::instantiate()`. The big issue with that approach is, how do we ensure that the post-init method is called from GDScript? This is not possible, and in fact a problem I had in the early days of gdext in 2022.


---


> On the other hand, the engine could also move the instance tracking to `ClassDB::set_object_extension_instance`.

This sounds like the better idea. I can talk to the Godot devs about the feasibility of this.



---

> Extension class instances constructed in rust cannot be reloaded

This doesn't seem to be true in general. For example, if you add `reloadable = true` to the `dodge-the-creeps` extension, and then add `#[export]` to the `Main` class' fields, those are reloaded.

Could you describe more clearly what exactly doesn't work? Ideally with a short example.

**Comment by TitanNano** [comment]
> ClassDB::instantiate() cannot be generally used, as it takes no arguments. It thus can't create Rust classes that don't have an init function, and requiring the latter is too limiting. For example, Gd::from_init_fn() allows the user to pass in arbitrary context.

Godot hot reloading requires a init method as it uses `recreate_instance_func` to recreate the extension part of a class instance.

> This doesn't seem to be true in general. For example, if you add reloadable = true to the dodge-the-creeps extension, and then add #[export] to the Main class' fields, those are reloaded.

> Could you describe more clearly what exactly doesn't work? Ideally with a short example.

The `dodge-the-creeps` example project does not contain any classes that are instantiated in rust. The `Main` class is a node subclass that is part of the scene and instanciated by the egnine when the scene tree is loaded. What I was refering to are GodotClasses which have been defined in rust and instanciated in rust code via a function on `Gd`.

**Comment by obvious5211** [comment]
Hi!

I ran into the same issues as @TitanNano. I confirm that using Godot's latest nighty build( v4.3.dev.custom_build [6118592c6] for my case), the hot reload work even with Godot instantiated classes.
