### ISSUE TITLE
`ConvertError` cannot easily be constructed by user?

### ISSUE THREAD

**Issue by bluenote10** [godot-rust/gdext#643]
I'm trying to migrate the following code to the latest version:

```rust
impl FromGodot for DragEventKind {
    fn try_from_godot(d: i32) -> Result<Self, ConvertError> {
        match d {
            0 => Ok(DragEventKind::DragStart),
            1 => Ok(DragEventKind::Drag),
            2 => Ok(DragEventKind::DragEnd),
            _ => Err(ConvertError::new()),
        }
    }
}
```

`ConvertError::new()` seems to have disappeared, and I cannot find a simple way to construct a `ConvertError`. The constructors that would be appropriate seem to be private. There is `ConvertError::with_cause` but I don't have a `Box<dyn Error + Send + Sync>`.

Searching the repo I've seen this pattern:

```rust
impl FromGodot for Vector2Axis {
    fn try_from_godot(via: Self::Via) -> Result<Self, ConvertError> {
        Self::try_from_ord(via).ok_or_else(|| FromGodotError::InvalidEnum.into_error(via))
    }
}
```

But `FromGodotError` also seems to be private.

Am I missing something or is this really no longer constructible on user side?

**Comment by lilizoey** [comment]
This was changed in #634, im not entirely sure why though? Or well apparently there is [this comment](https://github.com/godot-rust/gdext/blob/9900076363aa6a33b42f5251c8d7a052551251ef/godot-core/src/builtin/meta/godot_convert/convert_error.rs#L26) (added in #634):

```rs
// Constructors are private (or hidden) as only the library or its proc-macros should construct this type.
```

Which is a weird change to make imo, when i made the `ConvertError` type the intent was that people could use it to provide some custom errors in their manual `FromGodot` impls. That's why the `FromGodot` impl is hardcoded to return this error type instead of something more generic, because it's publicly constructible. Otherwise what are people supposed to do if they wanna convert a godot-type into their own custom type? Should they implement `TryFrom` and do like `foo.try_into()` instead? @Bromeon idk what your intent was here

**Comment by Bromeon** [comment]
@bluenote10 Since you are an active user of the `ConvertError` API, #644 might also interest you.
