### ISSUE TITLE
Attaching a Rust script to nodes of different types

### ISSUE THREAD

**Issue by ttencate** [godot-rust/gdext#73]
I'm working on a planet-scale game, for which Godot's 32-bit `Vector3` type is not precise enough. (I know about `precision=double` but it's pretty new, so I don't want to rely on it yet.)

The way I can deal with this is Godot 3 using GDNative is, I create a native `Transform64` class in Rust that contains the transform in 64-bit precision. In `Transform64::_process`, it will call `set_transform()` on its base node with the latest transform, suitably shifted to some origin that is close to the player before rounding to 32-bits. `Transform64` also offers an API containing e.g. `distance64(other: Transform64): float`.

The key here is that `Transform64` can be added to any node that inherits from `Spatial`. It could be a `RigidBody`, a `Camera` or `Spatial` itself. Essentially it acts as a mixin. Presumably, I can also inherit GDScripts from it, so I can write the higher-level functionality in GDScript (but I haven't tried this).

This doesn't seem to be so easy to do with GDExtension. My current workaround is to inherit `Transform64` from `Node` and add it as a child on any `Spatial`-derived node, reaching up with `get_parent()` to set the transform. The drawback is that `distance64()` and all the other methods can't be called on the root of the scene anymore, because it now lives in a child node. I have to write `self.transform64.distance64(other.transform64)` instead of simply `self.distance64(other)`.

According to [this comment](https://github.com/godotengine/godot/issues/66231#issuecomment-1362107615), it should already be possible to create your own scripting language, so maybe that API could be used to make certain Rust classes "act" like a script.

**Comment by astrale-sharp** [comment]
That might solve the hot reloading part as well no?

**Comment by ttencate** [comment]
Hot reloading will still require support from the engine, which is currently missing.

**Comment by Bromeon** [comment]
I think the request to use _classes_ in the way described is incompatible with how GDExtension works. In GDNative, user code ran as scripts, so the above workflow was easily achievable. In GDExtension however, the default way to run Rust code is via classes, which are first-class citizens and can be used as nodes in Godot. However, attaching a class to another node needs to go via child relation.

What _is_ possible is to write a custom scripting layer, which should essentially enable scripting semantics. Since this issue has been opened, the `ScriptInstance` API has been added, which should allow for this.
