### ISSUE TITLE
Consistent by-value and by-ref parameters for geometric types

### ISSUE THREAD

**Issue by Ughuuu** [godot-rust/gdext#749]
I am trying to make a physics server 2d and physics server 3d, and I want to use:
```
Rect2
Aabb
```

If I look at the docs, it says Aabb is the 3d counterpart of Rect2.

The method for merge of Aabb is:
```rust
pub fn merge(&self, b: &Aabb) -> Self {
```

The method for merge for Rect2 is:
```rust
pub fn merge(&self, b: Rect2) -> Self {
```

Could the 2 change so either both have reference or neither have reference for the parameter b?

**Comment by Bromeon** [comment]
This is a wider issue than `merge`, we need to establish a clear policy when to use by-value and by-ref for geometric types.

So far, the idea was that `Rect2` is by-value, because it has the same size as `Vector4`, and vectors are always by-value for convenience. However, this is not reflected in `Rect2`'s current `&self` receivers.

In general, things could be more consistent. I compiled an overview of the parameter passing in our builtin types:

| Type | Words (à 4 bytes) | Parameter |
| --- | --- | --- |
| [Vector2](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Vector2.html), [Vector2i](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Vector2i.html) | 2 | by-value |
| [Vector3](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Vector3.html), [Vector3i](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Vector3i.html) | 3 | by-value |
| [Vector4](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Vector4.html), [Vector4i](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Vector4i.html) | 4 | by-value |
| [Quaternion](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Quaternion.html) | 4 | by-value |
| [Color](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Color.html) | 4 | by-value |
| [Rect2](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Rect2.html) | 4 | by-ref (mostly) |
| [Rect2i](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Rect2i.html) | 4 | by-ref (mostly) |
| [Aabb](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Aabb.html) | 6 | by-ref |
| [Plane](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Plane.html) | 4 | by-ref |
| [Transform2D](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Transform2D.html) | 6 | mixed |
| [Basis](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Basis.html) | 9 | mixed |
| [Transform3D](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Transform3D.html) | 12 | mixed |
| [Projection](https://godot-rust.github.io/docs/gdext/master/godot/builtin/struct.Projection.html) | 16 | by-ref |

"mixed" means by-value is used if the return type is `Self`, by-ref otherwise.

**Comment by Bromeon** [comment]
Some more input on this, in terms of performance?

I checked glam, and it seems:
- All vectors use by-val, even [`DVec4`](https://docs.rs/glam/latest/glam/f64/struct.DVec4.html) -- 8 words
- All matrices use by-ref, even [`Mat2`](https://docs.rs/glam/latest/glam/f32/struct.Mat2.html) -- 4 words
- [`Quat`](https://docs.rs/glam/latest/glam/f32/struct.Quat.html) uses by-val -- 4 words

So after consistency changes, we do the same for the above types, and additionally treat `Aabb`, `Plane`, `Rect2`, `Rect2i` as by-val.
