### ISSUE TITLE
`@rpc` support and examples

### ISSUE THREAD

**Issue by StepanTheGreat** [godot-rust/gdext#784]
Hello, I've been trying to find any way to use godot's RPCs in `gdext`, but couldn't find any example of it (searched for it in the issues and features under this repo as well). It would be great to see a working `gdext` example like in [`gdnative`](https://github.com/godot-rust/gdnative/tree/master/examples/rpc), or at least some code examples to see how to declare RPC functions? So far I was only able to find the Base `rpc` method, but that's about it.

**Comment by Bromeon** [comment]
We don't have such examples because there's no dedicated RFC support in gdext yet.

Would you be interested in participating in a design discussion about `@rpc` & Co. in Rust? We could probably use this issue -- and as you stated, there's some prior work in gdnative :slightly_smiling_face:

**Comment by StepanTheGreat** [comment]
Sure. I personally think this could be indeed almost the same macro as in gdnative's RPC, though with *required* (debatable) fields like packet reliability, remote/local code execution and channel ID.  I'm new to rust's macros in general, though I think something like this could be possible: 
```rust
#[func(rpc=("authority", "reliable", "remote", 1))]
fn ping(&mut self);
```
(Might not be convenient to paste default values ("authority" for example) each time though)

**Comment by toolness** [comment]
For what it's worth, if you _really_ need RPC _right now_, it is technically possible to do, it's just not type-checked very well.  I think I found a thread in the Discord discussing how to do it, but the TLDR is that you can use code like this in your `INode::ready()` implementation:

```rust
self.base_mut().rpc_config(
            "proxy_request_to_server_internal".into(),
            dict! {
                "rpc_mode": RpcMode::ANY_PEER,
                "transfer_mode": TransferMode::RELIABLE,
                "call_local": false,
            }
            .to_variant(),
        );
```

In this case `proxy_request_to_server_internal` is a method you've defined on your class.

You can also call RPC methods on your class like this:

```rust
self.base_mut().rpc_id(
                            1, // Send to server only, its ID is always 1.
                            "proxy_request_to_server_internal".into(),
                            &[
                                request_id.to_variant(),
                                serialized_request_body.into_godot().to_variant(),
                            ],
                        );
```

Again, it's all terribly un-ergonomic and not well-typed, but it gets the job done if you need it right this minute.

**Comment by ambeeeeee** [comment]
I did some initial work for implementing an `#[rpc]` attribute in the macros, I wanted to discuss the syntax and finer implementation details before I did anything else with it. The code's in [this branch](https://github.com/ambeeeeee/gdext/tree/rpc-attr-poc) but it's not really important to the discussion.

It's a parsing implementation detail and easily changed, but I'd propose this syntax:
```rs
#[godot_api]
impl MyRefCounted {
    #[rpc(mode = RpcMode::AUTHORITY, transfer_mode = TransferMode::RELIABLE, call_local = true, transfer_channel = 10)]
    pub fn test() {}
}
```
(it should be noted that `call_local` is not implemented in my branch)

In this case `#[rpc]` would imply `#[func]`, since I'd expect you need to expose your function properly to Godot for it to be callable by name. You can configure `#[rpc]` with the same values you can use for `#[func]` on top of the extra rpc-specific configuration.

I'd be glad to carry the PR further into implementation and out of "here's how it could work and a half implemented base" but the syntax to target is an open question.

Also I could use some clarification on how I should inject the logic that calls [`rpc_config`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-rpc-config). Right now [I added a method to `godot::obj::cap::ImplementsGodotApi`](https://github.com/ambeeeeee/gdext/commit/7f253021344126e7640658cfe1c000c17a9a1580#diff-9614fc7970cb5a04b8113272b4d81278f095a3aa3596799585762cf6999c6a04R552) but its not injected into any initialization process for the node, so it doesn't do anything on top of potentially being a wildly incorrect solution.

**Comment by Bromeon** [comment]
> In this case `#[rpc]` would imply `#[func]`, since I'd expect you need to expose your function properly to Godot for it to be callable by name. You can configure `#[rpc]` with the same values you can use for `#[func]` on top of the extra rpc-specific configuration.

So, the arguments that you can provide to `#[func]` and `#[rpc]` should be non-overlapping, so people definitely need to write `#[func]` as soon as they use one of its keys.

On the topic of `#[rpc]` implying `#[func]` (without keys): it may be a bit more convenient, but it does make it harder to discover all registered functions (e.g. using ripgrep or IDE search). The only place where we do this is with `#[var]` and `#[export], and in this case both are well-known, whereas `#[rpc]` is something that many users do not encounter. So maybe we should keep the two independent from the start (always requiring `#[func]`) and then consider ergonomic improvements later, or what do you think?

**Comment by ambeeeeee** [comment]
> On the topic of #[rpc] implying #[func] (without keys): it may be a bit more convenient, but it does make it harder to discover all registered functions (e.g. using ripgrep or IDE search). 

The main reason I had `#[rpc]` imply `#[func]` was because that would mean every single use of `#[rpc]` would have an associated `#[func]` attribute as well. There's nothing inherently wrong with this, and I agree that there are benefits around having both expressed individually. It might be a small headache for users when they try to use `#[rpc]` without `#[func]` and are greeted with an error telling them to also add `#[func]`.

Making the decision to require both isn't permanent. `#[rpc]` could be made to imply `#[func]` down the line, likely without any backwards compatibility issues. It would incur a permanent maintenance overhead though. The semver implications are typically up for debate as well.

> This looks great! You should be able to reuse most of KvParser's functionality. The enums should be treated as regular expressions without "magic" (don't try to parse them, just forward).

Right now I have it forwarding the `TokenStream` from each attribute key's value directly into the codegen, My thinking is that I'm trying to preserve the span but I might be making the wrong assumptions here.

The main problem with my implementation right now is that the way it's implemented directly generates a Dictionary with the `dict!{}` macro which means that you can pass in any type you want as a value, because its not checked for its type. You'd probably end up with a runtime error which we can likely avoid at compile-time.

<details>
<summary>Example of the above</summary>

```rs
#[godot_api]
impl MyRefCounted {
    #[rpc(
        mode = String::from("completely wrong value"), 
        transfer_mode = 0.1f32, 
        call_local = true, 
        transfer_channel = 10
    )]
    pub fn test() {}
}
```

</details>

I've done some work with type safety in macros outside of this crate so I'm familiar with the general strategies but I'd like to know how you think I should approach this so it fits with the rest of the code. 

> I assume you have default values for those, which match Godot?

I haven't tracked down the defaults or determined whether we can omit entries and have Godot provide its defaults. Honestly, it sounds like the path forward here would be determining the defaults and I'll do that.

**Comment by Bromeon** [comment]
> I've done some work with type safety in macros outside of this crate so I'm familiar with the general strategies but I'd like to know how you think I should approach this so it fits with the rest of the code.

Probably a small builder would be appropriate:
```rs
pub struct RpcBuilder {
    mode: RpcMode,
    transfer_mode: TransferMode,
    call_local: bool,
    transfer_channel: u32,
}

impl RpcBuilder {
    pub fn mode(mut self, mode: RpcMode) -> Self {
        self.mode = mode;
        self
    }

    pub fn transfer_mode(mut self, transfer_mode: TransferMode) -> Self {
        self.transfer_mode = transfer_mode;
        self
    }

    pub fn call_local(mut self, call_local: bool) -> Self {
        self.call_local = call_local;
        self
    }

    pub fn transfer_channel(mut self, transfer_channel: u32) -> Self {
        self.transfer_channel = transfer_channel;
        self
    }

    // Doesn't even need build() method.
}
```

According to [these docs](https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html), the defaults are:
```rs
impl Default for RpcBuilder {
    fn default() -> Self {
        RpcBuilder {
            mode: RpcMode::AUTHORITY,
            transfer_mode: TransferMode::UNRELIABLE,
            call_local: false,
            transfer_channel: 0,
        }
    }
}
```

Usage:
```rs
// Generated code by the macro -- one call for each key:
let rpc = RpcBuilder::default()
	.mode(RpcMode::AUTHORITY)
	.transfer_mode(TransferMode::RELIABLE)
	.call_local(true)
	.transfer_channel(10);

// The API that actually registers this with Godot then accesses the builder directly:
let transfer_mode = rpc.transfer_mode;
...
```

**Comment by ambeeeeee** [comment]
I implemented the type safety using the struct as you suggested, feedback to the user on type mismatch looks great so no more concerns there. `call_local` is also properly implemented now. 

I'll get `#[func]` and `#[rpc]` split up properly and following the requirements we've converged on. Then I'll integrated rpc registration into the Node's lifecycle and open a PR so we can iterate on the implementation details. 
I plan to PR the book to add a section on RPC and work on the macro documentation after opening the feature PR. 

<details>
<summary>Generated code after the latest changes</summary>

```rs
#[godot_api]
impl MyRefCounted {
    #[rpc(
        mode = RpcMode::AUTHORITY,
        transfer_mode = TransferMode::RELIABLE,
        transfer_channel = 10,
        call_local = true
    )]
    pub fn test() {}

    #[rpc(
        mode = RpcMode::ANY_PEER,
        transfer_mode = TransferMode::UNRELIABLE_ORDERED,
        transfer_channel = 15,
        call_local = false
    )]
    pub fn foo() {}
}
```

```rs
fn __register_rpc(base: &mut ::godot::obj::Gd<::godot::classes::Node>) {
    let rpc_configuration = ::godot::obj::RpcArgs {
        mode: RpcMode::AUTHORITY,
        transfer_mode: TransferMode::RELIABLE,
        call_local: true,
        transfer_channel: 10,
        ..Default::default()
    }
    .into_dictionary();
    base.rpc_config("test".into(), rpc_configuration.to_variant());
    let rpc_configuration = ::godot::obj::RpcArgs {
        mode: RpcMode::ANY_PEER,
        transfer_mode: TransferMode::UNRELIABLE_ORDERED,
        call_local: false,
        transfer_channel: 15,
        ..Default::default()
    }
    .into_dictionary();
    base.rpc_config("foo".into(), rpc_configuration.to_variant());
}
```

`RpcArgs::into_dictionary` is a function that just creates the dictionary form of Rpc arguments. 

</details>

**Comment by Bromeon** [comment]
> I'd say it's better to use key-value for explicitness, and I worry about the potential to pick up gdscript syntax for the sake of picking up gdscript syntax.

I was thinking about this, too; but I think key-value is better for two reasons:
- consistency with rest of our proc-macro API
- values can be specified in any order (there are no mistakes in reordering)
- you can omit keys that are not at the end, and we will use the right default
- `transfer_channel = 10` is more explicit than just `10`.

I know it's a bit more wordy and there's some RTFM involved when translating GDScript for the first time, but I'm not sure if it's that bad. We should probably see how users work with this.

---

Another thing I was briefly thinking about:
```rs
   #[rpc(
        mode = AUTHORITY, // omit RpcMode::
        transfer_mode = RELIABLE, // omit TransferMode::
        transfer_channel = 10,
        call_local = true
    )]
```
However I'm not sure if it's a good idea. While we can easily inject the enum prefixes, this prevents use cases like:
```rs
const MY_MODE: RpcMode = RpcMode::AUTHORITY;

 #[rpc(mode = MY_MODE)]
```
which would btw partially address the "reuse config" point you mentioned. But I agree, if people find themselves repeating a lot, we could still later add a `config = ` key and make `RpcConfig` public.

---

Could you also add tests where only some RPC config keys are specified? 

Is there a way to test this at all? There seems to be no getter counterpart to [`Node::rpc_config`](https://godot-rust.github.io/docs/gdext/master/godot/classes/struct.Node.html#method.rpc_config), so how to verify that the keys are properly applied?

**Comment by ambeeeeee** [comment]
> However I'm not sure if it's a good idea. While we can easily inject the enum prefixes, this prevents use cases like:
> ...
> which would btw partially address the "reuse config" point you mentioned. But I agree, if people find themselves repeating a lot, we could still later add a config = key and make RpcConfig public.

I didn't even think about that, we could make `RpcConfig` public ahead of time to allow them to use this pattern if they desire the ability to have one definition shared across multiple rpcs, and this obviously wouldn't work with the omission of the enum prefixes.
```rs
const MY_RPC_CONFIG: RpcConfig = RpcConfig {
    mode: RpcMode::AUTHORITY,
    transfer_mode: TransferMode::RELIABLE,
    transfer_channel: 10,
    call_local: true
}

#[rpc(mode = MY_RPC_CONFIG.mode, transfer_mode = MY_RPC_CONFIG.transfer_mode, transfer_channel = MY_RPC_CONFIG.transfer_channel, call_local = MY_RPC_CONFIG.call_local]
```

There's... definitely [a function in the Godot source code to get rpc configuration](https://github.com/godotengine/godot/blob/0e9caa2d9cb20737f8dcf08b75fcf2a78d980569/scene/main/node.h#L695) but it doesn't seem like it'll help.

If we can write tests that actually use Godot's RPC, we can at the very least test calls where `call_local = true`, but we can't test `mode`'s value since we'd be the authority, and `transfer_channel` would have no effect. Integration tests for this are definitely going to be a challenge.

**Comment by Bromeon** [comment]
> I didn't even think about that, we could make `RpcConfig` public ahead of time to allow them to use this pattern if they desire the ability to have one definition shared across multiple rpcs

You're right, maybe we should just make it public then?
Should we then also provide `config =` directly?

I think the [`tools` module](https://godot-rust.github.io/docs/gdext/master/godot/tools/index.html) may be a candidate for the `RpcConfig` struct.

(The `config =` key could btw be a separate PR, so we can finish this faster :slightly_smiling_face: )

---

> If we can write tests that actually use Godot's RPC (by being the host, so we don't need any networking), we can at the very least test calls where `call_local = true`, but we can't test `mode`'s value since we'd be the authority, and `transfer_channel` would have no effect. Integration tests for this are definitely going to be a challenge.

Yes, this is going to be both development- and maintenance-heavy; I'd rather avoid it. Maybe we can open a PR to Godot to expose this functionality. I can try to find out if there's a reason why it's not exposed :thinking:

**Comment by ambeeeeee** [comment]
Added `config = RpcConfigValue` named attribute parameter and moved `RpcConfig` over to the tools module. Here's where the syntax is at, collapsed since the number of examples is growing quite large.
<details>
<summary>Click to view syntax</summary>

```rs
const BARE_CONST_CONFIG: RpcConfig = RpcConfig {
    mode: RpcMode::AUTHORITY,
    transfer_mode: TransferMode::UNRELIABLE,
    call_local: false,
    transfer_channel: 1,
};

#[godot_api]
impl MyRefCounted {
    #[rpc(
        mode = RpcMode::AUTHORITY,
        transfer_mode = TransferMode::RELIABLE,
        transfer_channel = 10,
        call_local = true
    )]
    pub fn test() {}

    #[rpc(
        mode = RpcMode::ANY_PEER,
        transfer_mode = TransferMode::UNRELIABLE_ORDERED,
        transfer_channel = 15,
        call_local = false
    )]
    pub fn foo() {}

    // Rpc + func not supported yet
    #[rpc(call_local = true)]
    #[func(rename = "PascalCaseEndpoint")]
    pub fn snake_case_endpoint() {

    }

    const ASSOCIATED_CONFIG: RpcConfig = RpcConfig {
        mode: RpcMode::AUTHORITY,
        transfer_mode: TransferMode::UNRELIABLE,
        call_local: false,
        transfer_channel: 1,
    };

    #[rpc(config = Self::ASSOCIATED_CONFIG)]
    pub fn new_config_endpoint() {}

    #[rpc(config = BARE_CONST_CONFIG)]
    pub fn other_config_endpoint() {}
}
```

</details>

This is where we're at syntax wise. `#[rpc]` and `#[func]` aren't able to be defined at the same time yet, since I need to adjust how I am processing the rpc attribute to associate the invocation with a `#[func]` attribute, especially for `rename` support. 

I also need to add a check to prevent the `#[rpc]` functions from having a return type, as that is not supported by the RPC mechanism Godot exposes. That's a pretty simple problem to solve, but its worth mentioning.

I'll open the PR following the codegen changes for `#[rpc]` as that concludes the code side of things and we can get eyes on it while I work on some documentation and an example.

I also would propose the same method we come up with to make signals more ergonomic be used to make calling the RPC methods more ergonomic. However I think we should actually implement that after we get support for the `rpc` attribute in, since there are still reasonable methods to call RPC. I just wanted to mention that for your consideration as you're thinking about signal ergonomics.

**Comment by Bromeon** [comment]
This looks great, thanks a lot! 👍 

One small possibility is that Godot would extend the `RpcConfig` in the future, and then we'd have a breaking change. This could be technically addressed by a builder and `#[non_exhaustive]`, but I think we don't need it for now. If such a change happens, we could also introduce it across a minor version boundary -- maybe even good to notify people that there's now a new option.

**Comment by Bromeon** [comment]
@ambeeeeee Have you had a chance to follow up on this yet? 🙂

**Comment by Houtamelo** [comment]
I propose allowing the following, which aligns with GDScript's style:
```rust
#[rpc("any_peer", "reliable", "call_local", channel = 0)]
fn my_rpc_call(&mut self) {
    //..
}

const SHARED_RPC_ARGS: RpcArgs = RpcArgs { .. };

#[rpc(args = SHARED_RPC_ARGS)]
fn my_rpc_call(&mut self) {
    //..
}

#[rpc(args = SHARED_RPC_ARGS, "any_peer")] // compiler error, can't have both args constant and individual
fn my_rpc_call(&mut self) {
    //..
}

#[func(gd_self)] // #[func] can be specified to provide additional arguments, otherwise it's implied with default ones
#[rpc("any_peer")]
fn my_rpc_call(&mut self) {
    //..
}
```

I prefer having a separate attribute because:
- Avoids breaking changes
- #[func] has other options that the user might want to specify

If there's no #[func] attribute, then it's implied with default arguments.

The RpcArgs struct would be the one agreed on the previous answers.

**Comment by Houtamelo** [comment]
> @ambeeeeee's previous suggestion included this syntax:
> 
> ```rust
> #[godot_api]
> impl MyRefCounted {
>     #[rpc(mode = RpcMode::AUTHORITY, transfer_mode = TransferMode::RELIABLE, call_local = true, transfer_channel = 10)]
>     pub fn test() {}
> }
> ```
> 
> What's your view on that vs. yours, @Houtamelo?
Imo it's too long with no real benefit.

> If we keep it shorter, then we should not quote keys as strings; no other proc-macro API of gdext does this currently. Syntax cohesion with GDScript is less important than internal consistency within the library. That is, instead of:
> 
> ```rust
> #[rpc("any_peer", "reliable", "call_local", channel = 0)]
> fn my_rpc_call(&mut self)
> ```
> 
> it would be
> 
> ```rust
> #[rpc(any_peer, reliable, call_local, channel = 0)]
> fn my_rpc_call(&mut self)
> ```
Looks good, I'm in favor of that.

**Comment by Bromeon** [comment]
Sounds good to me, you can gladly go ahead with a PR :blush:

**Comment by Houtamelo** [comment]
> Note that you essentially have [3 enum parameters](https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html#remote-procedure-calls) with 2-3 variants each:
> 
> 
> And 2 of those are encoded in [`RpcMode`](https://godot-rust.github.io/docs/gdext/master/godot/classes/multiplayer_api/struct.RpcMode.html) and [`TransferMode`](https://godot-rust.github.io/docs/gdext/master/godot/classes/multiplayer_peer/struct.TransferMode.html).

What about `sync`, should we add an enum for that too?
```rust
pub enum SyncMode {
        CallLocal,
        CallRemote,
}
```

**Comment by Bromeon** [comment]
I think the idea was to follow the dictionary used in [`Node::rpc_config()`](https://docs.godotengine.org/en/stable/classes/class_node.html#class-node-method-rpc-config), which has enums for `rpc_mode` and `transfer_mode`, but `bool` for `call_local`.

That also reminds me why the original key was named `config` and not `args`: `#[rpc(config = ...)]` then becomes a very direct wrapper on top of `Node::rpc_config()`.
