### ISSUE TITLE
A class that inherits from Button , displayed as Node ?

### ISSUE THREAD

**Issue by zhmt** [godot-rust/gdext#814]
```
#[derive(GodotClass)]
#[class(init, base = Button)]
struct JoyStick {

  base: Base<Button>,
}
```
It should be displayed with a icon of Button, right?
But it is displayed with a icon of Node.

And  properties "Theme overrides" (under group Control)  in inspector lost .
Any node inherits from Control, should have these properties.

godot 4.2.2 stable.

**Comment by Bromeon** [comment]
Theme overrides: https://github.com/godot-rust/gdext/issues/213

Nodes not having their parents' icon: https://github.com/godotengine/godot/issues/90367
Please comment on this Godot issue, to make sure it's not lost in the sea of issues.

Since both problems are already tracked elsewhere, I'll close this.
