### ISSUE TITLE
How to use godot api: load_threaded-request

### ISSUE THREAD

**Issue by cherish-ltt** [godot-rust/gdext#907]
I want to load resources through asynchronous backend. I found the 'load ' function, which is blocking. How to use non-blocking methods to load resources, such as godot API: load_threaded_request

**Comment by MrJoermungandr** [comment]
Hey! :)
I would recommend reading the book https://godot-rust.github.io/book/godot-api/functions.html#singletons here is a link to the singleton chapter :) also consider joining the discord for receiving help (https://discord.com/invite/aKUCJ8rJsc). That out of the way: you can look into the Godot Docs to find: the ResourceLoader class (https://docs.godotengine.org/en/stable/classes/class_resourceloader.html). it has the Method load_threaded_request. Now since you've read the book and it states we access singletons via: SingetonName::singeton() we can transfer that knowledge to : `ResourceLoader::singleton().load_threaded_request()` (use the_ex method for default parameter extension)

**Comment by Bromeon** [comment]
Did enabling that feature work?

**Comment by cherish-ltt** [comment]
> Did enabling that feature work?

I don't know how to use it

**Comment by Bromeon** [comment]
https://godot-rust.github.io/docs/gdext/master/godot/#cargo-features

If you don't know how to use Cargo features in general, I recommend checking the official Rust book :slightly_smiling_face:

I'll close this, as the API you requested is present in godot-rust. Of course, feel free to ask further questions if anything is unclear!

**Comment by cherish-ltt** [comment]
> https://godot-rust.github.io/docs/gdext/master/godot/#cargo-features
> 
> If you don't know how to use Cargo features in general, I recommend checking the official Rust book 🙂
> 
> I'll close this, as the API you requested is present in godot-rust. Of course, feel free to ask further questions if anything is unclear!

 Thank you!!!
