### ISSUE TITLE
Godot rust object access performance

### ISSUE THREAD

**Issue by Phreakyx** [godot-rust/gdext#911]
Hello everyone,

I want to firstly preface this to say that I am not sure if this is an actual issue or a limitation of the language bindings or even something wrong that I am doing so please have that in mind.

I am a working C++ and Unreal dev and took the opportunity to learn both Godot and Rust.
I made a very simple test to basically test the overhead of different languages like C++, C# and GDScript.
My test was the following:
1. Create a Player class that extends Node2D
2. Create 2 variables. NodeArray which would house a number of Node2D objects. MaxNodes to tell how much Node2D objects we will put in the array and work with. Default I went with 100000.
3. On the ready() method I do a for loop which creates a Node2D, adds it as a child to the Player and then adds the reference to the NodeArray.
4. On the process_physics() method I take the current time. Do a for loop that cycles through the NodeArray and sets a position of the Node2D array element to Vector2 { x: 0.01, y: 0 }. Take another current time and print the time it took to do all this in the console.

Here is what happened. When I did this in GDScript I took a baseline duration which was 16-17 ms. Afterwards when I applied this in C# it took ~20ms. Then doing this in C++ was as expected faster than all of these and it only took 11-12 ms. The issue I got is when I tried to run this in Rust it took 31ms and that is with an optimization since I usually take the current position of the Node2D element and add the Vector2 to it but when I did that in Rust it required me to clone() the mutable variable which made it take 39ms. So I decided to remove the clone() which took the time down to ~31ms.

Note: Running an algorithm like [segmented_sieve](https://www.geeksforgeeks.org/segmented-sieve/) works absolutely great which tells me it has something to do with accessing properties of Godot or interacting with its API in some way.

I am applying my test code here. It is not pretty or anything but it should work.
Rust:
[lib.txt](https://github.com/user-attachments/files/17269103/lib.txt)
C++:
[gdperformanceheader.txt](https://github.com/user-attachments/files/17269106/gdperformanceheader.txt)
[gdperformancecpp.txt](https://github.com/user-attachments/files/17269108/gdperformancecpp.txt)
C#:
[CsTest.txt](https://github.com/user-attachments/files/17269110/CsTest.txt)
GDScript:
[gdscript_test.txt](https://github.com/user-attachments/files/17269114/gdscript_test.txt)

Feel free to correct me if I am doing anything wrong. I had to rename all this to txt to be able to upload.

Thank you in advance!

**Comment by sogon-human** [comment]
Is using `Array` a hard requirement? If not, you can probably replace `Array` with `Vec` in rust version and get some speed improvement. On my machine, it went from ~38 ms to ~16-20 ms.

**Comment by Phreakyx** [comment]
Did some tests and it seems that the bottleneck comes from the Godot API or how the Rust code binds to the Godot one.
Interestingly C++ is faster using the GDExtension as well but maybe this is due to the fact that Godot is C++ itself?
Not sure will wait for a response.

**Comment by Brzusko** [comment]
Godot Rust Team are focusing on features atm. so, optimization will be targeted later. GDExtension is generating overhead with calling Godot Engine API. So, good solution is avoid godot api calls, same problem is addressed with C#.

**Comment by Phreakyx** [comment]
Oh, I understand completely. Now I know that this is a somewhat expected outcome. Even with that I am on average 4ms slower than C++ which is really good and a lot better than C#. It was a nice learning experience and I will be excited to see how much this grows. Good luck to all.

**Comment by Bromeon** [comment]
Thanks a lot for the feedback! As Brzusko mentioned, performance improvements are still ongoing. While feature development generally has priority, there have been [many improvements on the performance front](https://github.com/godot-rust/gdext/issues?q=is%3Aclosed+label%3Aperformance) (even more before we had the label). I also wrote a [devlog article](https://godot-rust.github.io/dev/ffi-optimizations-benchmarking/) a year ago about the challenges of FFI and performance.

One notable difference to godot-cpp is that godot-rust code is generally safe (unless you use `unsafe` or `experimental-threads` feature). For example, accessing a dead object is reliably causing panics instead of undefined behavior. You can also not mess with the reference count. There are also other runtime checks happening (see e.g. https://github.com/godot-rust/gdext/pull/546). My plan is to make this more configurable in the future, with reasonable defaults, e.g. no or only minimal checks in Release mode.

So I'd recommend to check this particular case again once we allow turning off runtime checks, so you compare apples to apples. In the meantime, if you can isolate other concrete FFI calls that are much slower than they should be, feel free to report them! :slightly_smiling_face:  Please use inline code if possible (with Rust code tags), or if you attach files, choose the `.rs` ending instead of `.txt`.

**Comment by Phreakyx** [comment]
Thank you for the detailed information. I read the devlog article on FFI and certainly it looks like it is not the issue especially since the issues mentioned in the article are already closed in their github issue pages. I will certainly be interested to see the performance with these checks disabled in release mode as they may be the final straw to having performance on point with the C++ implementation. As for Debug it is very nice to have this keeping with the Rust promise of being safe and not causing undefined behavior. I will be keeping an eye on the progress.
Keep up the great work!
