### ISSUE TITLE
Can not find any macro named #[func] 

### ISSUE THREAD

**Issue by cu8code** [godot-rust/gdext#924]
I am following the book to create a node with custom methods
but it seems there is something wrong when I try to use `#[func]`

```rust
use sqlite_vec::sqlite3_vec_init;
use rusqlite::{ffi::sqlite3_auto_extension, Connection};
use godot::{classes::*, prelude::*};
use zerocopy::IntoBytes;

#[godot_api]
impl VectorDB {
    #[func]
    fn insert_embeding(self, data:PackedInt32Array){
        let arr = data.to_vec();
        let bytes = arr.as_bytes();
        let mut smt = self.connection.prepare("INSERT INTO vec_items(rowid, embedding) VALUES (?, ?)").expect("failed to create prepare statement");
        smt.execute(rusqlite::params![0, bytes.as_bytes()]).expect("failed to execute statement");
    }
}
```

```error
error: custom attribute panicked
  --> src/lib.rs:39:1
   |
39 | #[godot_api]
   | ^^^^^^^^^^^^
   |
   = help: message: Receiver not supported
```
![image](https://github.com/user-attachments/assets/0bd498ab-8de8-4be4-9b81-3ac6735b7c60)

**Comment by Houtamelo** [comment]
"Receiver" is the variable a method is being called with, in `insert_embeding` that would be `self`.

`self` is not a supported receiver because that would imply consuming a Godot class, which isn't allowed when interfacing with Godot since the concept of consuming doesn't exist in their "land".

To fix this, use either:
- `&self`
- `&mut self`
- `#[func(self_gd)]` with `Gd<Self>`

**Comment by cu8code** [comment]
Thx for the help!
